const KEY='fuvarszervezo_v11';const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const VEHICLE_TYPES=['3.5 T dobozos autó','3.5 T plató autó','7.5 tonnás dobozos autó','7.5 tonnás platós autó','7.5 tonnás emelőhátfalas autó','7.5 tonnás KCR-es autó','12 tonnás dobozos autó','12 tonnás platós autó','12 tonnás emelőhátfalas autó','12 tonnás KCR-es autó','24 tonnás kamion'];
let state={projects:[],suppliers:[],recipients:[],vehicles:[],orders:[],settings:{baseAddress:'2310 Szigetszentmiklós, Kereskedő utca 2.'},aliases:{projects:{},suppliers:{}},geo:{}};
let maps={},masterType='projects',mediaRecorder=null,audioChunks=[],audioBlob=null,importOrders=[],reviewQueue=[],reviewIndex=0,deferredPrompt=null;
const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const today=()=>localISO(new Date()),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[_.,;:()[\]{}\/\\-]+/g,' ').replace(/\s+/g,' ').trim()}
function last5(v=''){const d=String(v).replace(/\D/g,'');return d.slice(-5).padStart(5,'0')}
function dateVal(v){if(v===null||v===undefined||v==='')return'';if(v instanceof Date&&!isNaN(v))return localISO(v);if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''}const t=String(v).trim();let m=t.match(/^(\d{4})[.\-/](\d{1,2})[.\-/](\d{1,2})(?:\D|$)/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=t.match(/^(\d{1,2})[.\-/](\d{1,2})[.\-/](\d{4})(?:\D|$)/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return''}
function setScheduleParts(value=''){const m=String(value).match(/^(\d{4})-(\d{2})-(\d{2})$/);$('#scheduleYear').value=m?.[1]||'';$('#scheduleMonth').value=m?.[2]||'';$('#scheduleDay').value=m?.[3]||'';$('#scheduleDate').value=m?value:''}
function syncScheduleDate(){const y=$('#scheduleYear').value.replace(/\D/g,'').slice(0,4),m=$('#scheduleMonth').value.replace(/\D/g,'').slice(0,2),d=$('#scheduleDay').value.replace(/\D/g,'').slice(0,2);$('#scheduleYear').value=y;$('#scheduleMonth').value=m;$('#scheduleDay').value=d;if(y.length!==4||!m||!d)return false;const value=`${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`,dt=new Date(value+'T12:00:00');if(isNaN(dt)||localISO(dt)!==value)return false;$('#scheduleDate').value=value;return true}
function bindDateParts(){const y=$('#scheduleYear'),m=$('#scheduleMonth'),d=$('#scheduleDay');[[y,4,m],[m,2,d],[d,2,null]].forEach(([el,max,next])=>{el.addEventListener('input',()=>{el.value=el.value.replace(/\D/g,'').slice(0,max);if(el.value.length===max&&next)next.focus()});el.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!el.value){const prev=el===d?m:el===m?y:null;if(prev){e.preventDefault();prev.focus();prev.setSelectionRange(prev.value.length,prev.value.length)}}})})}
function defaultVehicles(){return[{id:'v-mario',driverName:'Márió',name:'Dobozos 1',type:'3.5 T dobozos autó',homeCity:'Vác',active:true},{id:'v-patrik',driverName:'Patrik',name:'Dobozos 2',type:'3.5 T dobozos autó',homeCity:'Kispest',active:true},{id:'v-martin',driverName:'Martin',name:'Ponyvás',type:'3.5 T plató autó',homeCity:'Felcsút',active:true}]}
function refreshMasterData(){if(state.masterDataVersion==='v14-20260717')return;state.recipients=(state.recipients?.length?state.recipients:(SEED_DATA.recipients||[]).map((x,i)=>({...x,id:'r'+i})));state.projects=(SEED_DATA.projects||[]).map((x,i)=>({...x,id:'p'+i,defaultRecipientId:''}));state.suppliers=(SEED_DATA.suppliers||[]).map((x,i)=>({...x,id:'s'+i,isCentral:!!x.site&&norm(x.site)==='kozpont',pickupNote:x.note||''}));state.projects.forEach(p=>{const r=state.recipients.find(x=>norm(x.project)===norm(p.name))||state.recipients.find(x=>norm(x.name)===norm(p.receiver));p.defaultRecipientId=r?.id||''});(state.orders||[]).forEach(o=>{const p=state.projects.find(x=>norm(x.name)===norm(o.projectName));if(p)o.projectId=p.id;const matches=state.suppliers.filter(x=>norm(x.name)===norm(o.pickupName));if(matches.length===1)o.supplierId=matches[0].id});state.aliases={projects:{},suppliers:{}};state.masterDataVersion='v14-20260717'}function load(){const raw=localStorage.getItem(KEY);if(raw){state=JSON.parse(raw);state.aliases=state.aliases||{projects:{},suppliers:{}};state.vehicles=state.vehicles||defaultVehicles();state.orders=state.orders||[];refreshMasterData();save(false);return}state.recipients=(SEED_DATA.recipients||[]).map((x,i)=>({...x,id:'r'+i}));state.vehicles=defaultVehicles();state.orders=[];refreshMasterData();save(false)}
function save(renderNow=true){localStorage.setItem(KEY,JSON.stringify(state));if(renderNow)render()}
function activeVehicles(){return state.vehicles.filter(v=>v.active)}
function marioVehicle(){return activeVehicles().find(v=>norm(v.driverName).includes('mario'))||state.vehicles.find(v=>norm(v.driverName).includes('mario'))||null}
function selectedDate(){return $('#workDate').value||today()}
function dayOrders(vehicleId=null,date=selectedDate()){return state.orders.filter(o=>o.scheduleDate===date&&(!vehicleId||o.vehicleId===vehicleId))}
function option(v,t,sel=''){return`<option value="${esc(v)}" ${String(v)===String(sel)?'selected':''}>${esc(t)}</option>`}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));function restoreFile(file){const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result),mode=confirm('OK = összevonás, Mégse = teljes csere')?'merge':'replace';if(mode==='replace')state=incoming;else{state.orders=[...state.orders,...(incoming.orders||[]).filter(x=>!state.orders.some(y=>y.id===x.id))];state.projects=[...state.projects,...(incoming.projects||[]).filter(x=>!state.projects.some(y=>norm(y.name)===norm(x.name)))];state.suppliers=[...state.suppliers,...(incoming.suppliers||[]).filter(x=>!state.suppliers.some(y=>norm(y.name)===norm(x.name)&&norm(y.address)===norm(x.address)))];state.recipients=[...state.recipients,...(incoming.recipients||[]).filter(x=>!state.recipients.some(y=>norm(y.name)===norm(x.name)&&norm(y.project)===norm(x.project)))]}save();alert('Adatok betöltve.')}catch(e){alert('Hibás mentési fájl.')}};r.readAsText(file)}
$('#recordStart').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>e.data.size&&audioChunks.push(e.data);mediaRecorder.onstop=()=>{audioBlob=new Blob(audioChunks,{type:mediaRecorder.mimeType||'audio/webm'});$('#audioPreview').src=URL.createObjectURL(audioBlob);$('#audioPreview').classList.remove('hidden');$('#recordStatus').textContent='Felvétel elkészült.';stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();$('#recordStart').disabled=true;$('#recordStop').disabled=false;$('#recordStatus').textContent='Felvétel folyamatban…'}catch(e){alert(e.message)}};
$('#recordStop').onclick=()=>{if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();$('#recordStart').disabled=false;$('#recordStop').disabled=true};
$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));scrollTo(0,0);render()}
function render(){applyAfterFourRule();renderRoutes();renderOrders();renderMasters();renderVehicles();renderDriver();fillSelectors();$('#baseAddress').value=state.settings.baseAddress}
function longReason(name=''){const n=norm(name);let m=n.match(/(?:^|[^0-9])([456])\s*(?:m|meter)(?:es|eres)?\b/);if(m)return`${m[1]} méteres szálanyag`;m=n.match(/\b(4000|5000|6000)\s*mm\b/);if(m&&/(szal|cso|acel|rud|profil)/.test(n))return`${+m[1]/1000} méteres szálanyag`;return''}
function canCarryLong(v){return/(plato|kcr|kamion)/.test(norm(v.type))}
function centralSupplier(name){const group=state.suppliers.filter(s=>norm(s.name)===norm(name));return group.find(s=>s.isCentral)||group[0]||null}
function renderRoutes(){const vehicles=activeVehicles();$('#routes').innerHTML=vehicles.map(v=>{const list=dayOrders(v.id).sort((a,b)=>(+a.sequence||999)-(+b.sequence||999));return`<section class="route"><header class="route-head"><h2><input value="${esc(v.driverName)}" onchange="renameDriver('${v.id}',this.value)"></h2><small>${esc(v.name)} · ${esc(v.type)} · ${list.length} fuvar</small><div class="route-summary" id="summary-${v.id}"></div></header><div id="map-${v.id}" class="map"></div><div id="route-${v.id}" class="route-list">${bubbles(list)}</div></section>`}).join('')||'<div class="notice">Nincs aktív jármű.</div>';setTimeout(initMaps,30);setTimeout(initSortables,40);setTimeout(updateSummaries,60)}
function itemNoteSummary(o){return(o.items||[]).map((it,i)=>it.itemNote?`<p class="item-note-preview"><b>${i+1}. tétel megjegyzés:</b> ${esc(it.itemNote)}</p>`:'').join('')}
function bubbles(list){if(!list.length)return'<div class="notice">Nincs fuvar.</div>';return list.map((o,i)=>`<article class="bubble ${o.completed?'done':''}" data-id="${o.id}"><span class="drag">☷</span><h3>${i+1}. ${esc(o.orderNo)} · ${esc(o.projectName||'Egyedi úticél')}</h3><p><b>Felrakó:</b> ${esc(o.pickupName||'Nincs megadva')} · ${esc(o.pickupAddress||'')}</p><p><b>Lerakó:</b> ${esc(o.dropAddress||'Nincs megadva')}</p>${o.pickupNote?`<p><b>Felrakói megj.:</b> ${esc(o.pickupNote)}</p>`:''}${o.note?`<p><b>Fuvar megjegyzés:</b> ${esc(o.note)}</p>`:''}${itemNoteSummary(o)}<div class="tags"><span class="tag">${o.items?.length||0} tétel</span>${o.longMaterialReason?`<span class="tag long">${esc(o.longMaterialReason)}</span>`:''}${o.requestedDeadline?`<span class="tag ${o.scheduleDate>o.requestedDeadline?'warn':''}">${o.requestedDeadline}</span>`:''}</div><div class="bubble-actions"><button onclick="editOrder('${o.id}')">Szerkesztés</button><button onclick="openItems('${o.id}')">Tételek</button><button onclick="openCamera('${o.id}')">📷 Kamera</button></div><button class="complete-button ${o.completed?'done':''}" onclick="toggleComplete('${o.id}')">${o.completed?'✓':'○'}</button><button class="trash" onclick="deleteOne('${o.id}')">🗑</button></article>`).join('')}
window.renameDriver=(id,name)=>{const v=state.vehicles.find(x=>x.id===id);if(v){v.driverName=name.trim()||v.driverName;save()}};
function initSortables(){activeVehicles().forEach(v=>{const el=$('#route-'+v.id);if(!el)return;new Sortable(el,{group:'vehicles',animation:180,handle:'.drag',onEnd:e=>{const o=state.orders.find(x=>x.id===e.item.dataset.id);if(o)o.vehicleId=e.to.id.replace('route-','');activeVehicles().forEach(x=>{$$('#route-'+x.id+' .bubble').forEach((n,i)=>{const r=state.orders.find(o=>o.id===n.dataset.id);if(r)r.sequence=i+1})});save()}})})}
async function geo(addr){if(!addr)return null;if(state.geo[addr])return state.geo[addr];try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=hu&q='+encodeURIComponent(addr));const j=await r.json();if(j[0]){state.geo[addr]=[+j[0].lat,+j[0].lon];save(false);await new Promise(r=>setTimeout(r,1050));return state.geo[addr]}}catch{}return null}
function initMaps(){activeVehicles().forEach(v=>{if(maps[v.id])maps[v.id].remove();maps[v.id]=L.map('map-'+v.id).setView([47.45,19.04],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(maps[v.id]);drawMap(v.id)})}
async function roadRoute(pts){if(pts.length<2)return null;try{const c=pts.map(p=>`${p[1]},${p[0]}`).join(';');const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${c}?overview=full&geometries=geojson`);const j=await r.json();return j.routes?.[0]||null}catch{return null}}
async function drawMap(id){const map=maps[id],pts=[];const base=await geo(state.settings.baseAddress);if(base)pts.push(base);for(const o of dayOrders(id).sort((a,b)=>(+a.sequence||999)-(+b.sequence||999))){const p=await geo(o.dropAddress);if(p){pts.push(p);L.marker(p).addTo(map).bindPopup(`<b>${esc(o.orderNo)} · ${esc(o.projectName||'Egyedi úticél')}</b><br>${esc(o.dropAddress||'')}${o.recipientName?`<br>Átvevő: ${esc(o.recipientName)}`:''}${o.note?`<br>Megjegyzés: ${esc(o.note)}`:''}`)}}if(pts.length){const rr=await roadRoute(pts);const coords=rr?rr.geometry.coordinates.map(c=>[c[1],c[0]]):pts;const line=L.polyline(coords,{weight:4}).addTo(map);map.fitBounds(line.getBounds(),{padding:[20,20]})}}
async function vehicleHome(v){const known={vac:'Vác',kispest:'1191 Budapest, Kispest',felcsut:'Felcsút'};return await geo(known[norm(v.homeCity)]||v.homeCity||state.settings.baseAddress)||await geo(state.settings.baseAddress)}
function dist(a,b){if(!a||!b)return 999;const R=6371,r=Math.PI/180,d1=(b[0]-a[0])*r,d2=(b[1]-a[1])*r,x=Math.sin(d1/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(d2/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
async function balance(){const active=activeVehicles();if(!active.length)return alert('Nincs aktív jármű.');const orders=state.orders.filter(o=>o.scheduleDate===selectedDate()),longCars=active.filter(canCarryLong);for(const o of orders){if(o.longMaterialReason){const target=longCars.find(v=>norm(v.driverName).includes('martin'))||longCars[0];if(target)o.vehicleId=target.id}}
const homes={};for(const v of active)homes[v.id]=await vehicleHome(v);const loads=Object.fromEntries(active.map(v=>[v.id,orders.filter(o=>o.vehicleId===v.id&&o.longMaterialReason).length*2]));for(const o of orders.filter(o=>!o.longMaterialReason)){const p=await geo(o.pickupAddress||o.dropAddress);const ranked=active.map(v=>({v,score:(loads[v.id]||0)*12+dist(homes[v.id],p)})).sort((a,b)=>a.score-b.score);o.vehicleId=ranked[0].v.id;loads[o.vehicleId]=(loads[o.vehicleId]||0)+2}active.forEach(v=>dayOrders(v.id).forEach((o,i)=>o.sequence=i+1));save();alert('A fuvarokat az aktív autók, a sofőrök indulási helye és a terhelés alapján szétosztottam.')}
async function optimizeAll(){for(const v of activeVehicles()){const orders=dayOrders(v.id);let current=await geo(state.settings.baseAddress),left=[];for(const o of orders)left.push({o,p:await geo(o.dropAddress)});const ordered=[];while(left.length){left.sort((a,b)=>dist(current,a.p)-dist(current,b.p));const n=left.shift();ordered.push(n.o);if(n.p)current=n.p}ordered.forEach((o,i)=>o.sequence=i+1)}save()}
async function updateSummaries(){for(const v of activeVehicles()){const orders=dayOrders(v.id),pick=new Set(orders.map(o=>norm(o.pickupAddress)).filter(Boolean)),drop=new Set(orders.map(o=>norm(o.dropAddress)).filter(Boolean));const el=$('#summary-'+v.id);if(el)el.textContent=`${pick.size} felrakó · ${drop.size} lerakó · kb. ${Math.max(0,orders.length*35)} perc rakodás`}}
function toggleComplete(id){const o=state.orders.find(x=>x.id===id);if(!o)return;o.completed=!o.completed;o.completedAt=o.completed?new Date().toISOString():'';if(o.completed)(o.items||[]).forEach(i=>i.received=true);save()}
function applyAfterFourRule(){const now=new Date();if(now.getHours()<16)return;const d=today(),next=new Date();next.setDate(next.getDate()+1);const nd=next.toISOString().slice(0,10);let changed=false;state.orders.forEach(o=>{if(o.scheduleDate===d&&!o.completed&&!o.carriedAfter16){o.scheduleDate=nd;o.carriedAfter16=true;changed=true}});if(changed){localStorage.setItem(KEY,JSON.stringify(state));$('#dayWarning').classList.remove('hidden');$('#dayWarning').textContent='A 16:00 után nem teljesített mai fuvarokat a program áthelyezte a következő napra.'}}
function renderOrders(){const q=norm($('#orderSearch').value),vf=$('#orderVehicleFilter').value;const rows=state.orders.filter(o=>(!q||norm(JSON.stringify(o)).includes(q))&&(!vf||o.vehicleId===vf)).sort((a,b)=>a.scheduleDate.localeCompare(b.scheduleDate));$('#orderList').innerHTML=rows.map(o=>`<article class="card"><h3>${esc(o.orderNo)} · ${esc(o.projectName||'Egyedi úticél')}</h3><p>${o.scheduleDate} · ${esc(state.vehicles.find(v=>v.id===o.vehicleId)?.driverName||'Nincs kiosztva')}</p><p>${esc(o.pickupName||'')} → ${esc(o.dropAddress||'')}</p><div class="card-actions"><button onclick="editOrder('${o.id}')">Szerkesztés</button><button onclick="openItems('${o.id}')">Tételek</button><button onclick="deleteOne('${o.id}')">Törlés</button></div></article>`).join('')||'<div class="notice">Nincs találat.</div>'}
function renderVehicles(){$('#vehicleList').innerHTML=state.vehicles.map(v=>`<article class="card vehicle-card ${v.active?'':'inactive'}"><div><h3>${esc(v.driverName)} · ${esc(v.name)}</h3><p>${esc(v.type)} · ${esc(v.homeCity||'')}</p><div class="card-actions"><button onclick="editVehicle('${v.id}')">Szerkesztés</button></div></div><label class="switch"><input type="checkbox" ${v.active?'checked':''} onchange="toggleVehicle('${v.id}',this.checked)"> Aktív</label></article>`).join('')}
window.toggleVehicle=(id,val)=>{const v=state.vehicles.find(x=>x.id===id);if(v){v.active=val;if(!val){const active=state.vehicles.filter(x=>x.active);state.orders.filter(o=>o.vehicleId===id).forEach(o=>o.vehicleId=active[0]?.id||'')}save()}};
function renderDriver(){const vid=$('#driverVehicleSelect').value||activeVehicles()[0]?.id,date=$('#driverDate').value||selectedDate();const rows=dayOrders(vid,date).sort((a,b)=>(+a.sequence||999)-(+b.sequence||999));$('#driverTasks').innerHTML=rows.map((o,i)=>`<article class="driver-task ${o.completed?'done':''}"><h3>${i+1}. ${esc(o.orderNo)} · ${esc(o.projectName||o.dropAddress)}</h3><p><b>Felrakó:</b> ${esc(o.pickupName)} · ${esc(o.pickupAddress)}</p><p><b>Lerakó:</b> ${esc(o.dropAddress)}</p>${o.note?`<p><b>Megjegyzés:</b> ${esc(o.note)}</p>`:''}<button onclick="toggleComplete('${o.id}')">${o.completed?'✓ Minden tétel rendben':'○ Átvétel rendben'}</button><button class="secondary" onclick="openItems('${o.id}')">Tételek külön pipálása</button><button class="secondary" onclick="openCamera('${o.id}')">📷 Szállítólevél fotózása</button></article>`).join('')||'<div class="notice">Nincs feladat.</div>'}
function fillSelectors(){const vehicleOpts='<option value="">Nincs kiosztva</option>'+state.vehicles.map(v=>option(v.id,`${v.driverName} · ${v.name}${v.active?'':' (kikapcsolva)'}`)).join('');$('#vehicleId').innerHTML=vehicleOpts;$('#orderVehicleFilter').innerHTML='<option value="">Minden autó</option>'+state.vehicles.map(v=>option(v.id,v.driverName)).join('');$('#driverVehicleSelect').innerHTML=activeVehicles().map(v=>option(v.id,`${v.driverName} · ${v.name}`,$('#driverVehicleSelect').value)).join('');if(!$('#driverDate').value)$('#driverDate').value=selectedDate()}
function renderMasters(){const q=norm($('#masterSearch').value),arr=state[masterType].filter(x=>!q||norm(Object.values(x).join(' ')).includes(q));$('#masterList').innerHTML=arr.map(x=>`<article class="card"><h3>${esc(x.name)}</h3><p>${esc(x.address||x.project||'')} ${esc(x.phone||'')}</p>${masterType==='suppliers'?`<p>${x.isCentral?'★ Központi telephely':''}</p>`:''}<div class="card-actions"><button onclick="editMaster('${x.id}')">Szerkesztés</button><button onclick="deleteMaster('${x.id}')">Törlés</button></div></article>`).join('')||'<div class="notice">Nincs találat.</div>'}
function supplierOptions(sel=''){return'<option value="">Egyedi / nincs kiválasztva</option>'+state.suppliers.sort((a,b)=>a.name.localeCompare(b.name,'hu')).map(s=>option(s.id,`${s.name}${s.isCentral?' ★ központ':''} · ${s.address}`,sel)).join('')}
function projectOptions(sel=''){return'<option value="">Egyedi úticél</option>'+state.projects.sort((a,b)=>a.name.localeCompare(b.name,'hu')).map(p=>option(p.id,p.name,sel)).join('')}
function recipientOptions(project,sel=''){return'<option value="">Nincs átvevő</option>'+state.recipients.filter(r=>!project||norm(r.project)===norm(project)).map(r=>option(r.id,`${r.name} · ${r.phone||''}`,sel)).join('')}
function openOrder(o={}){$('#orderId').value=o.id||'';$('#orderTitle').textContent=o.id?'Fuvar szerkesztése':'Új fuvar';setScheduleParts(o.scheduleDate||selectedDate());fillSelectors();$('#vehicleId').value=o.vehicleId||'';$('#orderNo').value=o.orderNo||'';$('#deadline').value=o.requestedDeadline||'';$('#supplierId').innerHTML=supplierOptions(o.supplierId);$('#pickupAddress').value=o.pickupAddress||'';$('#pickupNote').value=o.pickupNote||'';$('#projectId').innerHTML=projectOptions(o.projectId);$('#dropAddress').value=o.dropAddress||'';$('#recipientId').innerHTML=recipientOptions(o.projectName,o.recipientId);$('#recipientName').value=o.recipientName||'';$('#recipientPhone').value=o.recipientPhone||'';$('#recipientEmail').value=o.recipientEmail||'';$('#pickupFrom').value=o.pickupFrom||'';$('#pickupTo').value=o.pickupTo||'';$('#dropFrom').value=o.dropFrom||'';$('#dropTo').value=o.dropTo||'';$('#orderNote').value=o.note||'';$('#orderDialog').showModal();setTimeout(()=>$('#scheduleYear').focus(),30)}
window.editOrder=id=>openOrder(state.orders.find(x=>x.id===id));
$('#orderForm').onsubmit=e=>{e.preventDefault();if(!syncScheduleDate())return alert('Adj meg érvényes szállítási dátumot.');const old=state.orders.find(x=>x.id===$('#orderId').value),s=state.suppliers.find(x=>x.id===$('#supplierId').value),p=state.projects.find(x=>x.id===$('#projectId').value),r=state.recipients.find(x=>x.id===$('#recipientId').value);const o={...old,id:old?.id||uid(),scheduleDate:$('#scheduleDate').value,vehicleId:$('#vehicleId').value,orderNo:last5($('#orderNo').value),requestedDeadline:$('#deadline').value,supplierId:s?.id||'',pickupName:s?.name||old?.pickupName||'',pickupAddress:$('#pickupAddress').value,pickupNote:$('#pickupNote').value,projectId:p?.id||'',projectName:p?.name||old?.projectName||'',dropAddress:$('#dropAddress').value,recipientId:r?.id||'',recipientName:$('#recipientName').value.trim()||r?.name||'',recipientPhone:$('#recipientPhone').value,recipientEmail:$('#recipientEmail').value,pickupFrom:$('#pickupFrom').value,pickupTo:$('#pickupTo').value,dropFrom:$('#dropFrom').value,dropTo:$('#dropTo').value,note:$('#orderNote').value,items:old?.items||[],completed:old?.completed||false,sequence:old?.sequence||999};const i=state.orders.findIndex(x=>x.id===o.id);if(i>=0)state.orders[i]=o;else state.orders.push(o);$('#orderDialog').close();save()}
$('#supplierId').onchange=()=>{const s=state.suppliers.find(x=>x.id===$('#supplierId').value);$('#pickupAddress').value=s?.address||'';$('#pickupNote').value=s?.pickupNote||''};
$('#projectId').onchange=()=>{const p=state.projects.find(x=>x.id===$('#projectId').value);$('#dropAddress').value=p?.address||'';$('#recipientId').innerHTML=recipientOptions(p?.name,p?.defaultRecipientId);const r=state.recipients.find(x=>x.id===p?.defaultRecipientId);$('#recipientName').value=r?.name||'';$('#recipientPhone').value=r?.phone||p?.phone||'';$('#recipientEmail').value=r?.email||''};
$('#recipientId').onchange=()=>{const r=state.recipients.find(x=>x.id===$('#recipientId').value);$('#recipientName').value=r?.name||$('#recipientName').value||'';$('#recipientPhone').value=r?.phone||'';$('#recipientEmail').value=r?.email||''};
function deleteOne(id){const o=state.orders.find(x=>x.id===id);if(o&&confirm(`Törlöd ezt a fuvart?\n${o.orderNo} · ${o.projectName||o.dropAddress}`)){state.orders=state.orders.filter(x=>x.id!==id);save()}}
function deleteAll(){if(!state.orders.length)return alert('Nincs törölhető fuvar.');if(confirm(`${state.orders.length} fuvar törlődik. Folytatod?`)&&prompt('Írd be: TÖRLÉS')?.toUpperCase()==='TÖRLÉS'){state.orders=[];save()}}
function openItems(id){const o=state.orders.find(x=>x.id===id);$('#itemsTitle').textContent=`${o.orderNo} · tételek`;$('#itemsBody').innerHTML=(o.items||[]).map((it,i)=>`<div class="item-row ${it.received?'done':''}"><input type="checkbox" ${it.received?'checked':''} onchange="toggleItem('${id}',${i},this.checked)"><div><b class="item-name">${esc(it.name)}</b><br>${esc(it.code)} · ${esc(it.qty)} ${esc(it.unit)} ${it.longMaterial?'· hosszú szál':''}<label class="item-note-edit">Tétel megjegyzés<textarea placeholder="Nincs megjegyzés" onchange="updateItemNote('${id}',${i},this.value)">${esc(it.itemNote||'')}</textarea></label></div></div>`).join('')||'<div class="notice">Nincs tétel.</div>';$('#itemsDialog').showModal()}
window.openItems=openItems;window.toggleItem=(id,i,val)=>{const o=state.orders.find(x=>x.id===id);o.items[i].received=val;o.completed=(o.items||[]).length>0&&o.items.every(x=>x.received);save(false);openItems(id)};window.updateItemNote=(id,i,val)=>{const o=state.orders.find(x=>x.id===id);if(!o||!o.items?.[i])return;o.items[i].itemNote=val;save(false);renderRoutes();renderOrders();};
function openCamera(id){const o=state.orders.find(x=>x.id===id);$('#cameraOrderId').value=id;$('#cameraTitle').textContent=`${o.orderNo} · szállítólevél`;$('#cameraPreview').innerHTML='';$('#cameraNote').value='';$('#cameraInput').value='';$('#cameraDialog').showModal()}
window.openCamera=openCamera;$('#cameraInput').onchange=e=>{$('#cameraPreview').innerHTML=[...e.target.files].map(f=>`<img src="${URL.createObjectURL(f)}">`).join('')};$('#cameraForm').onsubmit=e=>{e.preventDefault();const o=state.orders.find(x=>x.id===$('#cameraOrderId').value);o.deliveryReports=o.deliveryReports||[];o.deliveryReports.push({at:new Date().toISOString(),note:$('#cameraNote').value,photoCount:$('#cameraInput').files.length,hasAudio:!!audioBlob});$('#cameraDialog').close();save();alert('A fotó és megjegyzés helyben rögzítve.')};
function editVehicle(id){const v=state.vehicles.find(x=>x.id===id)||{};$('#vehicleTitle').textContent=v.id?'Jármű szerkesztése':'Új jármű';$('#editVehicleId').value=v.id||'';$('#driverName').value=v.driverName||'';$('#vehicleName').value=v.name||'';$('#vehicleType').innerHTML=VEHICLE_TYPES.map(t=>option(t,t,v.type)).join('');$('#homeCity').value=v.homeCity||'';$('#vehicleActive').checked=v.active!==false;$('#vehicleDialog').showModal()}
window.editVehicle=editVehicle;$('#vehicleForm').onsubmit=e=>{e.preventDefault();const id=$('#editVehicleId').value,v={id:id||uid(),driverName:$('#driverName').value,name:$('#vehicleName').value,type:$('#vehicleType').value,homeCity:$('#homeCity').value,active:$('#vehicleActive').checked};const i=state.vehicles.findIndex(x=>x.id===id);if(i>=0)state.vehicles[i]=v;else state.vehicles.push(v);$('#vehicleDialog').close();save()}
function masterFields(){if(masterType==='projects')return[['name','Projekt neve'],['address','Cím'],['defaultRecipientId','Alap átvevő']];if(masterType==='suppliers')return[['name','Cégnév'],['site','Telephely'],['address','Cím'],['pickupNote','Felrakói megjegyzés'],['isCentral','Központi telephely']];return[['project','Projekt'],['name','Átvevő neve'],['phone','Telefon'],['email','E-mail']]}
function openMaster(x={}){$('#masterTitle').textContent=x.id?'Szerkesztés':'Új adat';$('#editMasterId').value=x.id||'';$('#masterFields').innerHTML=masterFields().map(([k,l])=>{if(k==='defaultRecipientId')return`<label>${l}<select data-mf="${k}"><option value="">Nincs</option>${state.recipients.map(r=>option(r.id,`${r.name} · ${r.project}`,x[k])).join('')}</select></label>`;if(k==='isCentral')return`<label class="check"><input data-mf="${k}" type="checkbox" ${x[k]?'checked':''}> ${l}</label>`;return`<label>${l}<input data-mf="${k}" value="${esc(x[k]||'')}"></label>`}).join('');$('#masterDialog').showModal()}
window.editMaster=id=>openMaster(state[masterType].find(x=>x.id===id));window.deleteMaster=id=>{if(confirm('Törlöd?')){state[masterType]=state[masterType].filter(x=>x.id!==id);save()}};
$('#masterForm').onsubmit=e=>{e.preventDefault();const id=$('#editMasterId').value,obj={id:id||uid(),active:true};$$('[data-mf]').forEach(x=>obj[x.dataset.mf]=x.type==='checkbox'?x.checked:x.value.trim());if(masterType==='suppliers'&&obj.isCentral)state.suppliers.filter(s=>norm(s.name)===norm(obj.name)).forEach(s=>s.isCentral=false);const i=state[masterType].findIndex(x=>x.id===id);if(i>=0)state[masterType][i]={...state[masterType][i],...obj};else state[masterType].push(obj);$('#masterDialog').close();save()}
function headerMap(headers){const normalized=headers.map(norm),find=names=>normalized.findIndex(h=>names.map(norm).includes(h)),findExact=name=>normalized.findIndex(h=>h===norm(name));const supplierName=findExact('Ügyfél/raktár név');const map={doc:find(['Bizonylatszám']),topic:findExact('Témaszám név'),code:find(['Termék kód','Termékkód']),product:find(['Termék név','Terméknév']),supplier:supplierName,qty:find(['Tétel mennyiség']),unit:find(['M.e.']),deadline:find(['Kért szállítási határidő']),note:find(['Megjegyzés']),itemNote:find(['Tétel megjegyzés','Tételmegjegyzés','Tétel megjegyzése','Tételhez tartozó megjegyzés']),date:findExact('Dátum'),driver:find(['Sofőr','Gépkocsivezető','Járművezető'])};if(map.date<0&&headers.length>=2)map.date=headers.length-2;if(map.driver<0&&headers.length>=1)map.driver=headers.length-1;return map}
function similarity(a,b){a=norm(a);b=norm(b);if(a===b)return 1;const aw=a.split(' '),bw=b.split(' '),common=aw.filter(x=>bw.includes(x)).length;return common/Math.max(aw.length,bw.length)}
function projectMatch(topic){const alias=state.aliases.projects[norm(topic)];if(alias)return state.projects.find(p=>p.id===alias);const scores=state.projects.map(p=>({p,s:similarity(topic,p.name)})).sort((a,b)=>b.s-a.s);return scores[0]?.s>=.75&&(!scores[1]||scores[0].s-scores[1].s>.15)?scores[0].p:null}
function supplierMatch(name){const alias=state.aliases.suppliers[norm(name)];if(alias)return state.suppliers.find(s=>s.id===alias);const exact=state.suppliers.filter(s=>norm(s.name)===norm(name));if(exact.length===1)return exact[0];if(exact.length>1){const central=exact.filter(s=>s.isCentral);return central.length===1?central[0]:null}const companies=[...new Set(state.suppliers.map(s=>s.name))].filter(n=>norm(name).includes(norm(n))||norm(n).includes(norm(name)));if(companies.length!==1)return null;const matches=state.suppliers.filter(s=>norm(s.name)===norm(companies[0]));if(matches.length===1)return matches[0];const central=matches.filter(s=>s.isCentral);return central.length===1?central[0]:null}
async function readExcel(file){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}),h=headerMap(rows[0].map(String));if(h.topic<0||h.supplier<0)return alert('Hiányzó kötelező SERPA oszlop: Témaszám név vagy Ügyfél/raktár név.');if(h.date<0||norm(rows[0][h.date])!=='datum')return alert('Nem található a SERPA Dátum oszlopa.');const g={};for(const r of rows.slice(1)){const date=dateVal(r[h.date]);if(!date)continue;const no=last5(r[h.doc]),topic=String(r[h.topic]||''),sup=String(r[h.supplier]||''),key=[date,no,topic,sup].join('|'),lr=longReason(r[h.product]);if(!g[key])g[key]={id:uid(),scheduleDate:date,vehicleId:'',sequence:999,orderNo:no,topicName:topic,pickupName:sup,pickupAddress:'',pickupNote:'',projectName:'',dropAddress:'',recipientName:'',recipientPhone:'',recipientEmail:'',requestedDeadline:dateVal(r[h.deadline]),note:h.note>=0?String(r[h.note]||''):'',items:[],longMaterialReason:''};if(lr)g[key].longMaterialReason=lr;g[key].items.push({code:String(r[h.code]||''),name:String(r[h.product]||''),qty:r[h.qty],unit:String(r[h.unit]||''),itemNote:h.itemNote>=0?String(r[h.itemNote]||''):'',longMaterial:!!lr,received:false});if(h.driver>=0&&norm(r[h.driver]).includes('martin'))g[key].markedMartin=true}importOrders=Object.values(g);importOrders.forEach(o=>{const p=projectMatch(o.topicName),s=supplierMatch(o.pickupName);if(p){o.projectId=p.id;o.projectName=p.name;o.dropAddress=p.address;const rec=state.recipients.find(r=>r.id===p.defaultRecipientId);if(rec){o.recipientId=rec.id;o.recipientName=rec.name;o.recipientPhone=rec.phone;o.recipientEmail=rec.email}}if(s){o.supplierId=s.id;o.pickupName=s.name;o.pickupAddress=s.address;o.pickupNote=s.pickupNote||''}});const longCars=activeVehicles().filter(canCarryLong),martin=longCars.find(v=>norm(v.driverName).includes('martin'))||longCars[0];importOrders.forEach(o=>{if(o.markedMartin||o.longMaterialReason)o.vehicleId=martin?.id||''});$('#importPreview').textContent=`${importOrders.length} összesített rendelés. Bizonytalan/hiányos: ${importOrders.filter(needsReview).length}.`;$('#startReviewBtn').disabled=false}
function needsReview(o){return!o.projectId||!o.supplierId||!o.pickupAddress||!o.dropAddress||!o.vehicleId}
function startReview(){reviewQueue=importOrders.filter(needsReview);reviewIndex=0;if(!reviewQueue.length){finalizeImport();return}showReview()}
function showReview(){const o=reviewQueue[reviewIndex];$('#reviewTitle').textContent=`${o.orderNo} · ${o.topicName||'Egyedi'}`;$('#reviewCounter').textContent=`${reviewIndex+1} / ${reviewQueue.length}`;$('#reviewFields').innerHTML=`<label>Projekt<select id="rvProject" onchange="reviewProjectChanged()" class="${o.projectId?'':'review-error'}">${projectOptions(o.projectId)}</select></label><label>Lerakó cím<input id="rvDrop" class="${o.dropAddress?'':'review-error'}" value="${esc(o.dropAddress||'')}"></label><label>Beszállító<select id="rvSupplier" onchange="reviewSupplierChanged()" class="${o.supplierId?'':'review-error'}">${supplierOptions(o.supplierId)}</select></label><label>Felrakó cím<input id="rvPickup" class="${o.pickupAddress?'':'review-error'}" value="${esc(o.pickupAddress||'')}"></label><label>Jármű<select id="rvVehicle" class="${o.vehicleId?'':'review-error'}"><option value="">Később osztom ki</option>${activeVehicles().map(v=>option(v.id,`${v.driverName} · ${v.name}`,o.vehicleId)).join('')}</select></label><label>Fuvar megjegyzés<textarea id="rvNote">${esc(o.note||'')}</textarea></label>`;$('#reviewDialog').showModal()}
function reviewProjectChanged(){const p=state.projects.find(x=>x.id===$('#rvProject').value);if(!p)return;$('#rvDrop').value=p.address||'';const rec=state.recipients.find(r=>r.id===p.defaultRecipientId);if(rec){if($('#rvRecipient'))$('#rvRecipient').value=rec.id;if($('#rvPhone'))$('#rvPhone').value=rec.phone||''}}
function reviewSupplierChanged(){const s=state.suppliers.find(x=>x.id===$('#rvSupplier').value);if(!s)return;const c=centralSupplier(s.name)||s;$('#rvPickup').value=c.address||''}
function saveReview(){const o=reviewQueue[reviewIndex],p=state.projects.find(x=>x.id===$('#rvProject').value),s=state.suppliers.find(x=>x.id===$('#rvSupplier').value);o.projectId=p?.id||'';o.projectName=p?.name||o.topicName||'';o.dropAddress=$('#rvDrop').value;o.supplierId=s?.id||'';o.pickupName=s?.name||o.pickupName;o.pickupAddress=$('#rvPickup').value;o.vehicleId=$('#rvVehicle').value||marioVehicle()?.id||'';o.note=$('#rvNote').value;if(p)state.aliases.projects[norm(o.topicName)]=p.id;if(s)state.aliases.suppliers[norm(o.pickupName)]=s.id;reviewIndex++;if(reviewIndex>=reviewQueue.length){$('#reviewDialog').close();finalizeImport()}else showReview()}
function finalizeImport(){const mario=marioVehicle();importOrders.forEach(o=>{if(!o.vehicleId&&mario)o.vehicleId=mario.id});state.orders.push(...importOrders);importOrders=[];$('#importDialog').close();save();alert('Import beillesztve. A jármű nélkül továbbléptetett fuvarok Márió autójára kerültek, és később szerkeszthetők.')}
function exportExcel(){const rows=state.orders.filter(o=>o.scheduleDate===selectedDate());const wb=XLSX.utils.book_new(),main=[['Jármű','Sorrend','Rendelésszám','Felrakó','Felrakó cím','Projekt','Lerakó cím','Átvevő','Telefon','Időablak','Megjegyzés','Tétel megjegyzések']];rows.forEach(o=>main.push([state.vehicles.find(v=>v.id===o.vehicleId)?.driverName||'',o.sequence,o.orderNo,o.pickupName,o.pickupAddress,o.projectName,o.dropAddress,o.recipientName,o.recipientPhone,[o.pickupFrom&&`F ${o.pickupFrom}-${o.pickupTo}`,o.dropFrom&&`L ${o.dropFrom}-${o.dropTo}`].filter(Boolean).join('; '),o.note,(o.items||[]).map((i,n)=>i.itemNote?`${n+1}. ${i.itemNote}`:'').filter(Boolean).join(' | ')]));const items=[['Rendelésszám','Termékkód','Termék név','Mennyiség','M.e.','Tétel megjegyzés','Átvéve']];rows.forEach(o=>(o.items||[]).forEach(i=>items.push([o.orderNo,i.code,i.name,i.qty,i.unit,i.itemNote||'',i.received?'Igen':'Nem'])));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(main),'Fuvarok');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(items),'Tételek');XLSX.writeFile(wb,`${selectedDate()}_fuvarok.xlsx`)}
function exportPdf(){const rows=state.orders.filter(o=>o.scheduleDate===selectedDate()),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'});doc.text(`Fuvarok - ${selectedDate()}`,14,14);doc.autoTable({startY:20,head:[['Jármű','#','Rendelés','Felrakó','Lerakó','Átvevő','Megjegyzés','Tétel megjegyzések']],body:rows.map(o=>[state.vehicles.find(v=>v.id===o.vehicleId)?.driverName||'',o.sequence,o.orderNo,`${o.pickupName}\n${o.pickupAddress}`,`${o.projectName}\n${o.dropAddress}`,`${o.recipientName||''}\n${o.recipientPhone||''}`,o.note||'',(o.items||[]).map((i,n)=>i.itemNote?`${n+1}. ${i.itemNote}`:'').filter(Boolean).join('\n')]),styles:{fontSize:6.5}});doc.save(`${selectedDate()}_fuvarok.pdf`)}
function exportMenu(){const t=prompt('Export: excel vagy pdf','excel');if(norm(t).startsWith('p'))exportPdf();else exportExcel()}
function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fuvarszervezo-v11-telefonra.json';a.click()}
function restoreFile(file){const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result),mode=confirm('OK = összevonás, Mégse = teljes csere')?'merge':'replace';if(mode==='replace')state=incoming;else{state.orders=[...state.orders,...(incoming.orders||[]).filter(x=>!state.orders.some(y=>y.id===x.id))];state.projects=[...state.projects,...(incoming.projects||[]).filter(x=>!state.projects.some(y=>norm(y.name)===norm(x.name)))];state.suppliers=[...state.suppliers,...(incoming.suppliers||[]).filter(x=>!state.suppliers.some(y=>norm(y.name)===norm(x.name)&&norm(y.address)===norm(x.address)))];state.recipients=[...state.recipients,...(incoming.recipients||[]).filter(x=>!state.recipients.some(y=>norm(y.name)===norm(x.name)&&norm(y.project)===norm(x.project)))]}save();alert('Adatok betöltve.')}catch(e){alert('Hibás mentési fájl.')}};r.readAsText(file)}
$('#recordStart').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>e.data.size&&audioChunks.push(e.data);mediaRecorder.onstop=()=>{audioBlob=new Blob(audioChunks,{type:mediaRecorder.mimeType||'audio/webm'});$('#audioPreview').src=URL.createObjectURL(audioBlob);$('#audioPreview').classList.remove('hidden');$('#recordStatus').textContent='Felvétel elkészült.';stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();$('#recordStart').disabled=true;$('#recordStop').disabled=false;$('#recordStatus').textContent='Felvétel folyamatban…'}catch(e){alert(e.message)}};
$('#recordStop').onclick=()=>{if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();$('#recordStart').disabled=false;$('#recordStop').disabled=true};
$$('.nav').forEach(n=>n.onclick=()=>showPage(n.dataset.page));$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$$('[data-master]').forEach(b=>b.onclick=()=>{$$('[data-master]').forEach(x=>x.classList.toggle('active',x===b));masterType=b.dataset.master;renderMasters()});
$('#prevDay').onclick=()=>{const d=new Date(selectedDate()+'T12:00:00');d.setDate(d.getDate()-1);$('#workDate').value=d.toISOString().slice(0,10);render()};$('#nextDay').onclick=()=>{const d=new Date(selectedDate()+'T12:00:00');d.setDate(d.getDate()+1);$('#workDate').value=d.toISOString().slice(0,10);render()};$('#workDate').onchange=render;
$('#importBtn').onclick=()=>$('#importDialog').showModal();$('#excelInput').onchange=e=>readExcel(e.target.files[0]).catch(err=>alert(err.message));$('#startReviewBtn').onclick=startReview;$('#reviewForm').onsubmit=e=>{e.preventDefault();saveReview()};$('#reviewSkipBtn').onclick=saveReview;
$('#quickAddBtn').onclick=()=>openOrder({scheduleDate:selectedDate(),items:[]});$('#addOrderBtn').onclick=()=>openOrder({scheduleDate:selectedDate(),items:[]});$('#balanceBtn').onclick=balance;$('#optimizeBtn').onclick=optimizeAll;$('#exportBtn').onclick=exportMenu;$('#deleteAllBtn').onclick=deleteAll;
$('#orderSearch').oninput=renderOrders;$('#globalSearch').oninput=e=>{$('#orderSearch').value=e.target.value;showPage('orders');renderOrders()};$('#orderVehicleFilter').onchange=renderOrders;$('#addVehicleBtn').onclick=()=>editVehicle();$('#saveBaseBtn').onclick=()=>{state.settings.baseAddress=$('#baseAddress').value;save()};$('#driverVehicleSelect').onchange=renderDriver;$('#driverDate').onchange=renderDriver;
$('#addMasterBtn').onclick=()=>openMaster();$('#masterSearch').oninput=renderMasters;$('#backupBtn').onclick=backup;$('#restoreInput').onchange=e=>e.target.files[0]&&restoreFile(e.target.files[0]);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{deferredPrompt?.prompt();deferredPrompt=null};
bindDateParts();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();$('#workDate').value=today();$('#driverDate').value=today();render();