const KEY='fuvarszervezo_v2';const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let state={projects:[],suppliers:[],recipients:[],orders:[],settings:{baseAddress:'2310 Szigetszentmiklós, Kereskedő utca',vehicle1:'Dobozos 1',vehicle2:'Dobozos 2',vehicle3:'Ponyvás'}};
let tempImport=[],importView='orders',dbType='projects',deferredPrompt=null;
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function today(){return new Date().toISOString().slice(0,10)}
function load(){const r=localStorage.getItem(KEY);if(r)state=JSON.parse(r);else{state.projects=SEED_DATA.projects.map((x,i)=>({...x,id:'p'+i}));state.suppliers=SEED_DATA.suppliers.map((x,i)=>({...x,id:'s'+i}));state.recipients=SEED_DATA.recipients.map((x,i)=>({...x,id:'r'+i}));save(false)}}
function save(msg=false){localStorage.setItem(KEY,JSON.stringify(state));render();if(msg)alert('Mentve.')}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(v){if(!v)return'';if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''}const s=String(v).trim();const m=s.match(/(\d{4})[.\-/](\d{1,2})[.\-/](\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
function show(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));scrollTo(0,0);render()}
function dayOrders(){return state.orders.filter(o=>o.scheduleDate===$('#workDate').value)}
function render(){const date=$('#workDate').value||today();$('#workDate').value=date;const list=dayOrders();$('#dateTitle').textContent=new Intl.DateTimeFormat('hu-HU',{weekday:'long',month:'long',day:'numeric'}).format(new Date(date+'T12:00:00'));$('#baseText').textContent='Indulás: '+state.settings.baseAddress;$('#dayCount').textContent=list.length;$('#unassignedCount').textContent=list.filter(o=>!o.vehicle).length;$('#windowCount').textContent=list.filter(o=>o.pickupFrom||o.dropFrom).length;$('#importCount').textContent=list.reduce((a,o)=>a+(o.items?.length||0),0);
$('#vehicleCards').innerHTML=[1,2,3].map(n=>`<button class="vehicle" onclick="openVehicle('${n}')"><span class="ico">${n==3?'🚛':'🚚'}</span><span><b>${esc(state.settings['vehicle'+n])}</b><small>${list.filter(o=>o.vehicle==n).length} rendelés</small></span><span class="arrow">›</span></button>`).join('');
renderOrders();renderDb();renderImport();fillSettings()}
window.openVehicle=n=>{$('#orderVehicleFilter').value=n;show('orders')}
function renderOrders(){const q=($('#orderSearch').value||'').toLowerCase(),vf=$('#orderVehicleFilter').value;const rows=dayOrders().filter(o=>[o.orderNo,o.pickupName,o.projectName,o.dropAddress,o.recipientName].join(' ').toLowerCase().includes(q)&&(!vf||(vf==='none'?!o.vehicle:o.vehicle===vf))).sort((a,b)=>(+a.sequence||999)-(+b.sequence||999));$('#orderList').innerHTML=rows.length?rows.map(o=>`<article class="item ${o.vehicleNeed==='Csak ponyvás'?'tarp':''}"><div class="row"><div><h3>${esc(o.projectName||o.dropAddress)}</h3><p>${esc(o.pickupName)} → ${esc(o.dropAddress)}</p></div><span class="badge">${o.vehicle?state.settings['vehicle'+o.vehicle]:'Nincs autón'}</span></div><p><b>${esc(o.orderNo||'–')}</b> · sorrend: ${esc(o.sequence||'–')} ${o.pickupFrom?`· felvétel ${o.pickupFrom}-${o.pickupTo}`:''} ${o.dropFrom?`· lerakás ${o.dropFrom}-${o.dropTo}`:''}</p><p>${esc(o.recipientName||'')} ${esc(o.recipientPhone||'')}</p><div class="actions"><button onclick="editOrder('${o.id}')">Szerkesztés</button><button onclick="window.open('https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(o.dropAddress)}','_blank')">Térkép</button><button class="delete" onclick="deleteOrder('${o.id}')">Törlés</button></div></article>`).join(''):'<div class="notice">Erre a napra nincs megjeleníthető szállítás.</div>'}
function option(v,t,selected=''){return`<option value="${esc(v)}" ${String(v)===String(selected)?'selected':''}>${esc(t)}</option>`}
function populateOrderForm(o={}){$('#editOrderId').value=o.id||'';$('#scheduleDate').value=o.scheduleDate||$('#workDate').value;$('#vehicle').value=o.vehicle||'';$('#orderNo').value=o.orderNo||'';$('#sequence').value=o.sequence||'';$('#pickupType').value=o.pickupType||'supplier';fillPickupOptions(o.pickupId);$('#pickupAddress').value=o.pickupAddress||'';fillProjectOptions(o.projectId);$('#dropAddress').value=o.dropAddress||'';fillRecipientOptions(o.projectName,o.recipientId);$('#recipientPhone').value=o.recipientPhone||'';$('#recipientEmail').value=o.recipientEmail||'';$('#vehicleNeed').value=o.vehicleNeed||'Dobozos/Ponyvás';$('#hasPickupWindow').checked=!!o.pickupFrom;$('#pickupFrom').value=o.pickupFrom||'';$('#pickupTo').value=o.pickupTo||'';$('#pickupWindowBox').classList.toggle('hidden',!o.pickupFrom);$('#hasDropWindow').checked=!!o.dropFrom;$('#dropFrom').value=o.dropFrom||'';$('#dropTo').value=o.dropTo||'';$('#dropWindowBox').classList.toggle('hidden',!o.dropFrom);$('#note').value=o.note||''}
function fillPickupOptions(selected=''){const type=$('#pickupType').value;const arr=type==='supplier'?state.suppliers.filter(x=>x.active!==false):state.projects.filter(x=>x.active!==false&&(x.type==='felrakó'||x.type==='mindkettő'));$('#pickupSelect').innerHTML='<option value="">Válassz...</option>'+arr.map(x=>option(x.id,`${x.name}${x.site?' – '+x.site:''} | ${x.address}`,selected)).join('')}
function fillProjectOptions(selected=''){const arr=state.projects.filter(x=>x.active!==false&&(x.type==='lerakó'||x.type==='mindkettő'));$('#projectSelect').innerHTML='<option value="">Válassz projektet...</option>'+arr.map(x=>option(x.id,`${x.name} | ${x.address}`,selected)).join('')}
function fillRecipientOptions(projectName='',selected=''){const arr=state.recipients.filter(x=>x.active!==false&&(!projectName||x.project===projectName));$('#recipientSelect').innerHTML='<option value="">Válassz átvevőt...</option>'+arr.map(x=>option(x.id,`${x.name}${x.phone?' – '+x.phone:''}`,selected)).join('')}
window.editOrder=id=>{const o=state.orders.find(x=>x.id===id);$('#orderDialogTitle').textContent='Szállítás szerkesztése';populateOrderForm(o);$('#orderDialog').showModal()}
window.deleteOrder=id=>{if(confirm('Biztosan törlöd?')){state.orders=state.orders.filter(x=>x.id!==id);save()}}
function openNewOrder(){ $('#orderDialogTitle').textContent='Új szállítás';populateOrderForm({scheduleDate:$('#workDate').value});$('#orderDialog').showModal()}
$('#orderForm').onsubmit=e=>{e.preventDefault();const pid=$('#projectSelect').value,p=state.projects.find(x=>x.id===pid),pickType=$('#pickupType').value,pickArr=pickType==='supplier'?state.suppliers:state.projects,pick=pickArr.find(x=>x.id===$('#pickupSelect').value),rid=$('#recipientSelect').value,r=state.recipients.find(x=>x.id===rid);const obj={id:$('#editOrderId').value||uid(),scheduleDate:$('#scheduleDate').value,vehicle:$('#vehicle').value,orderNo:$('#orderNo').value,sequence:$('#sequence').value,pickupType:pickType,pickupId:pick?.id||'',pickupName:pick?.name||'',pickupAddress:$('#pickupAddress').value,projectId:p?.id||'',projectName:p?.name||'',dropAddress:$('#dropAddress').value,recipientId:r?.id||'',recipientName:r?.name||'',recipientPhone:$('#recipientPhone').value,recipientEmail:$('#recipientEmail').value,vehicleNeed:$('#vehicleNeed').value,pickupFrom:$('#hasPickupWindow').checked?$('#pickupFrom').value:'',pickupTo:$('#hasPickupWindow').checked?$('#pickupTo').value:'',dropFrom:$('#hasDropWindow').checked?$('#dropFrom').value:'',dropTo:$('#hasDropWindow').checked?$('#dropTo').value:'',note:$('#note').value};const i=state.orders.findIndex(x=>x.id===obj.id);if(i>=0)state.orders[i]=obj;else state.orders.push(obj);$('#orderDialog').close();save()}
$('#pickupType').onchange=()=>fillPickupOptions();$('#pickupSelect').onchange=()=>{const arr=$('#pickupType').value==='supplier'?state.suppliers:state.projects,x=arr.find(a=>a.id===$('#pickupSelect').value);$('#pickupAddress').value=x?.address||''};$('#projectSelect').onchange=()=>{const p=state.projects.find(x=>x.id===$('#projectSelect').value);$('#dropAddress').value=p?.address||'';fillRecipientOptions(p?.name||'');};$('#recipientSelect').onchange=()=>{const r=state.recipients.find(x=>x.id===$('#recipientSelect').value);$('#recipientPhone').value=r?.phone||'';$('#recipientEmail').value=r?.email||''};$('#hasPickupWindow').onchange=e=>$('#pickupWindowBox').classList.toggle('hidden',!e.target.checked);$('#hasDropWindow').onchange=e=>$('#dropWindowBox').classList.toggle('hidden',!e.target.checked);
function renderDb(){const q=($('#dbSearch').value||'').toLowerCase(),arr=state[dbType].filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));$('#dbList').innerHTML=arr.slice(0,250).map(x=>`<article class="item"><div class="row"><div><h3>${esc(x.name)}</h3><p>${esc(x.address||x.project||'')} ${esc(x.phone||'')}</p></div>${x.type?`<span class="badge">${esc(x.type)}</span>`:''}</div><div class="actions"><button onclick="editDb('${x.id}')">Szerkesztés</button><button class="delete" onclick="deleteDb('${x.id}')">Törlés</button></div></article>`).join('')||'<div class="notice">Nincs találat.</div>'}
function dbFields(x={}){if(dbType==='projects')return[['name','Projekt neve'],['address','Cím'],['receiver','Alap átvevő'],['phone','Telefonszám'],['type','Típus: felrakó / lerakó / mindkettő']];if(dbType==='suppliers')return[['name','Beszállító neve'],['site','Telephely'],['address','Cím'],['note','Megjegyzés']];return[['project','Projekt'],['name','Átvevő neve'],['phone','Telefon'],['role','Beosztás'],['email','E-mail'],['company','Cég'],['note','Megjegyzés']]}
function openDb(x={}){$('#dbTitle').textContent=x.id?'Adat szerkesztése':'Új adat';$('#dbEditIndex').value=x.id||'';$('#dbFields').innerHTML=dbFields(x).map(([k,l])=>`<label>${l}<input data-dbfield="${k}" value="${esc(x[k]||'')}"></label>`).join('');$('#dbDialog').showModal()}
window.editDb=id=>openDb(state[dbType].find(x=>x.id===id));window.deleteDb=id=>{if(confirm('Biztosan törlöd ezt az adatot?')){state[dbType]=state[dbType].filter(x=>x.id!==id);save()}}
$('#dbForm').onsubmit=e=>{e.preventDefault();const id=$('#dbEditIndex').value,obj={id:id||uid(),active:true};$$('[data-dbfield]').forEach(x=>obj[x.dataset.dbfield]=x.value.trim());const i=state[dbType].findIndex(x=>x.id===id);if(i>=0)state[dbType][i]=obj;else state[dbType].push(obj);$('#dbDialog').close();save()}
async function readExcel(file){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});if(rows.length<2)throw new Error('A fájl üres.');const head=rows[0].map(String);tempImport=[];for(const row of rows.slice(1)){const sched=fmtDate(row[row.length-1]);if(!sched)continue;const full=String(row[0]||''),digits=full.replace(/\D/g,''),orderNo=digits.slice(-4).padStart(4,'0');const supplier=String(row[2]||row[5]||'').trim();tempImport.push({id:uid(),scheduleDate:sched,orderNo,fullOrderNo:full,supplierName:supplier,reference:String(row[6]||''),requestedDate:fmtDate(row[8]),itemNo:String(row[9]||''),quantity:String(row[10]||''),vehicle:'',projectId:'',items:[]})}$('#importStatus').textContent=`${tempImport.length} ütemezett tételt találtam.`;renderImport()}
function groupedImport(){const m={};tempImport.forEach(x=>{const k=x.scheduleDate+'|'+x.orderNo+'|'+x.supplierName;if(!m[k])m[k]={...x,items:[]};m[k].items.push({itemNo:x.itemNo,quantity:x.quantity,reference:x.reference})});return Object.values(m)}
function renderImport(){const grouped=groupedImport();if(importView==='orders')$('#importPreview').innerHTML=grouped.map(g=>`<article class="group"><div class="row"><div><h3>${esc(g.orderNo)} · ${esc(g.supplierName)}</h3><p>${esc(g.scheduleDate)} · ${g.items.length} tétel</p></div><span class="badge">${g.vehicle?state.settings['vehicle'+g.vehicle]:'Nincs autón'}</span></div><div class="actions"><button onclick="setImportVehicle('${g.scheduleDate}|${g.orderNo}|${encodeURIComponent(g.supplierName)}','1')">Autó 1</button><button onclick="setImportVehicle('${g.scheduleDate}|${g.orderNo}|${encodeURIComponent(g.supplierName)}','2')">Autó 2</button><button onclick="setImportVehicle('${g.scheduleDate}|${g.orderNo}|${encodeURIComponent(g.supplierName)}','3')">Ponyvás</button></div></article>`).join('')||'<div class="notice">Nincs beolvasott adat.</div>';else $('#importPreview').innerHTML=[1,2,3,''].map(v=>`<article class="group"><h3>${v?state.settings['vehicle'+v]:'Nincs autóra osztva'}</h3>${grouped.filter(g=>(g.vehicle||'')===v).map(g=>`<p><b>${esc(g.orderNo)}</b> · ${esc(g.supplierName)} · ${g.items.length} tétel</p>`).join('')||'<p>Nincs tétel.</p>'}</article>`).join('')}
window.setImportVehicle=(key,v)=>{const [date,no,sup]=key.split('|'),supplier=decodeURIComponent(sup);tempImport.filter(x=>x.scheduleDate===date&&x.orderNo===no&&x.supplierName===supplier).forEach(x=>x.vehicle=v);renderImport()}
$('#commitImport').onclick=()=>{const grouped=groupedImport();grouped.forEach(g=>{const supplier=state.suppliers.find(s=>s.name.toLowerCase().includes(g.supplierName.toLowerCase().split(' ')[0])||g.supplierName.toLowerCase().includes(s.name.toLowerCase()));state.orders.push({id:uid(),scheduleDate:g.scheduleDate,vehicle:g.vehicle||'',orderNo:g.orderNo,sequence:'',pickupType:'supplier',pickupId:supplier?.id||'',pickupName:supplier?.name||g.supplierName,pickupAddress:supplier?.address||'',projectId:'',projectName:'',dropAddress:'',recipientId:'',recipientName:'',recipientPhone:'',recipientEmail:'',vehicleNeed:'Dobozos/Ponyvás',pickupFrom:'',pickupTo:'',dropFrom:'',dropTo:'',note:'SERPA import',items:g.items})});tempImport=[];save();alert('Az importált rendelések bekerültek a szállítások közé. A projektet és a telephelyet még ki kell választani.');show('orders')}
function fillSettings(){$('#baseAddress').value=state.settings.baseAddress;$('#vehicle1').value=state.settings.vehicle1;$('#vehicle2').value=state.settings.vehicle2;$('#vehicle3').value=state.settings.vehicle3}
$('#saveSettings').onclick=()=>{state.settings={baseAddress:$('#baseAddress').value,vehicle1:$('#vehicle1').value,vehicle2:$('#vehicle2').value,vehicle3:$('#vehicle3').value};save(true)}
$$('.nav').forEach(x=>x.onclick=()=>show(x.dataset.page));$$('[data-go]').forEach(x=>x.onclick=()=>show(x.dataset.go));$('#newOrderBtn').onclick=openNewOrder;$('#orderSearch').oninput=renderOrders;$('#orderVehicleFilter').onchange=renderOrders;$('#newDbBtn').onclick=()=>openDb();$('#dbSearch').oninput=renderDb;$$('[data-db]').forEach(x=>x.onclick=()=>{$$('[data-db]').forEach(y=>y.classList.remove('active'));x.classList.add('active');dbType=x.dataset.db;renderDb()});$$('[data-import-view]').forEach(x=>x.onclick=()=>{$$('[data-import-view]').forEach(y=>y.classList.remove('active'));x.classList.add('active');importView=x.dataset.importView;renderImport()});$$('[data-close]').forEach(x=>x.onclick=()=>$('#'+x.dataset.close).close());$('#excelFile').onchange=e=>readExcel(e.target.files[0]).catch(err=>$('#importStatus').textContent='Hiba: '+err.message);$('#workDate').onchange=render;$('#prevDay').onclick=()=>{const d=new Date($('#workDate').value+'T12:00:00');d.setDate(d.getDate()-1);$('#workDate').value=d.toISOString().slice(0,10);render()};$('#nextDay').onclick=()=>{const d=new Date($('#workDate').value+'T12:00:00');d.setDate(d.getDate()+1);$('#workDate').value=d.toISOString().slice(0,10);render()};$('#backupBtn').onclick=()=>save(true);$('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='fuvarszervezo-mentes.json';a.click()};$('#restoreFile').onchange=e=>{const r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();alert('Mentés visszatöltve.')};r.readAsText(e.target.files[0])};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();$('#workDate').value=today();render();